### ISSUE TITLE
500 on metadata query

### ISSUE THREAD

**Issue by bradleybeddoes** [ausaccessfed/saml-service#131]
Standard request to MDQ for all entities resulted in:

```
I, [2016-09-01T04:48:11.364484 #29794]  INFO -- : Completed 500 Internal Server Error in 1177ms (Models: 985.3ms)
F, [2016-09-01T04:48:11.365390 #29794] FATAL -- :
NoMethodError (undefined method `uri' for nil:NilClass):
  app/models/known_entity.rb:46:in `entity_id'
  lib/metadata/saml.rb:90:in `each'
  lib/metadata/saml.rb:90:in `group_by'
  lib/metadata/saml.rb:90:in `group_by_eid'
  lib/metadata/saml.rb:84:in `filter_known_entities'
  lib/metadata/saml.rb:63:in `block (2 levels) in entities_descriptor'
  lib/metadata/saml.rb:59:in `block in entities_descriptor'
  lib/metadata/saml.rb:54:in `entities_descriptor'
  app/controllers/concerns/metadata_query_caching.rb:59:in `block in cache_known_entities_response'
  app/controllers/concerns/metadata_query_caching.rb:58:in `cache_known_entities_response'
  app/controllers/metadata_query_controller.rb:121:in `create_known_entities_response'
  app/controllers/metadata_query_controller.rb:55:in `block in handle_entities_request'
  app/controllers/metadata_query_controller.rb:46:in `handle_entities_request'
  app/controllers/metadata_query_controller.rb:20:in `all_entities'
```

Which seems to indicate the associated EntityID has no URI value which is not a state that should ever exist.

FR pull was running at the time.

**Comment by bradleybeddoes** [comment]
I have tracked this back to here https://github.com/ausaccessfed/saml-service/blob/develop/app/jobs/concerns/etl/entity_descriptors.rb#L42

Upstream FR provided an EntityID that wasn't URI compliant, in this case the value `BXGOTY3T` was used for entityID URI (https://manager.test.aaf.edu.au/federationregistry/membership/serviceprovider/show/4965 and https://manager.test.aaf.edu.au/federationregistry/membership/entitydescriptor/show/4964). Data was modified by AAF support due to upstream client support outside of normal protections hence the flow on.

Regardless SS should not break on this case. Review import logic to ensure that invalid data at any layer spits the entire EntityID.

**Comment by bradleybeddoes** [comment]
Closed by https://github.com/ausaccessfed/saml-service/issues/132
